### ISSUE TITLE
HDMI输出无法使用

### ISSUE THREAD

**Issue by TegraFu** [lohcve/EFI_T470P_OC#3]
更新最新的EFI，HDMI输出无法使用，外接显示器插上HDMI，T470P中没有反应，好像识别不出来

**Comment by JiangLennon** [comment]
修改一下显卡注入。我的T470，修改deviceID为5916（up主是7700HQ，630，所以591b），同时修改con1的总线ID。
已实现内置、HDMI、Type-C三屏同时显示。（UP主的EFI使用con2对应Type-C也能显示的）

**Comment by lohcve** [comment]
已解决
